# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c2373191cee31aacf21a65917e1552b211e9c76707c18404a081e9317796a711b40c6cb935cb3a184424cbde9b58a204b003990a5e5b7a543a0a8308e7b8e2

test:
  secret_key_base: c4c02a94607c36ab957e79460ca6a61bb9c2da60cfaafbb4f2826652bfbbafa9c02d8efc1f575d441d9d77f2b69dd7e7b3d43ee94045a4abfee26e8a4e3b0e62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
