# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddc36c1b4faa03a75b359e8f173947602af67eea7ae54085b03c94a413ef624faf266d3a53d580c71fae3a1089ff2713c4ed382405a0837cca7f388c15f88b22

test:
  secret_key_base: 99ed04fbbc68aea5c56336cffd99048e0dbc9b90d580896cffafabda06e0a57ae80c37edc1588d6b62176db658f8feb380dece6f9802c5c653a8237cfb6dcb3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
